[theme]
primaryColor = "#FF4B4B"             # Keeping a nice accent color
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableStaticServing = true
